import { v4 as uuid } from "uuid";

export const products = [
  {
    _id: uuid(),
    title: "Casio",
    description: "A1486 Enticer Men's ( MTP-V002L-7B2UDF ) Analog Watch ",
    rating: "2",
    price: "5000",
    categoryName: "analog",
    inStock: true,
    fastdelivery: true,
  },
  {
    _id: uuid(),
    title: "Fastrack",
    description: "fasttrack 38024PP27 Minimalists digital Watch",
    rating: "3",
    price: "3000",
    categoryName: "digital",
    inStock: true,
    fastdelivery: false,
  },
  {
    _id: uuid(),
    title: "Fossil",
    description: "FS5708SET Neutra Chrono Analog Digital Watch",
    rating: "4",
    price: "10000",
    categoryName: "analog-digital",
    inStock: true,
    fastdelivery: true,
  },
  {
    _id: uuid(),
    title: "Fastrack",
    description: "38044PP01 Trendies Analog Watch",
    rating: "5",
    price: "3500",
    categoryName: "analog",
    inStock: true,
    fastdelivery: false,
  },
  {
    _id: uuid(),
    title: "Fossil",
    description: "FS5897 Retro Digital Watch ",
    rating: "2",
    price: "10000",
    categoryName: "digital",
    inStock: false,
    fastdelivery: false,
  },
  {
    _id: uuid(),
    title: "Casio",
    description: "AD250 (MWA-100H-1AVDF) Youth-Analog Analog Watch",
    rating: "3",
    price: "4000",
    categoryName: "analog",
    inStock: false,
    fastdelivery: true,
  },
  {
    _id: uuid(),
    title: "Titan",
    description: "AD250 (MWA-100H-1AVDF) Youth-Analog Analog Watch",
    rating: "3",
    price: "6500",
    categoryName: "analog",
    inStock: true,
    fastdelivery: true,
  },
  {
    _id: uuid(),
    title: "Titan",
    description: "AD250 (MWA-100H-1AVDF) Youth-digital Watch",
    rating: "5",
    price: "6000",
    categoryName: "digital",
    inStock: false,
    fastdelivery: true,
  },
];
